admin: zeewolf
commandprefix: '!'
connection:
  host: irc.freenode.net
  port: 6697
  secure: true
  debug: false
login:
  nickname: bot
  username: bot
  realname: node.js hyperstake bot
  nickserv_password: pass
channels:
  - '##tbtest'
log:
  file: tipbot.log
rpc:
  host: localhost
  port: 22555
  user: dogecoinrpc
  pass: pass
coin:
  withdrawal_fee: 2
  min_withdraw: 3
  min_confirmations: 3
  min_tip: 1
  min_rain: 1
  short_name: HYP
  full_name: HyperStake
webadmin:
  enabled: false
  port: 8080
  users:
    zeewolf: 123
timebomb:
  # min wires in game
  minWires: 3
  # max wires in game
  maxWires: 5
  # bomb disarm time [in milliseconds, 30000 = 30s]
  disarmTime: 30000
  # time for game decisions (not cutwire) - !again or !stop - [in milliseconds, 60000 = 60s]
  decisionTime: 60000
  # max pot size, when overflowed rain will happen
  maxPot: 300
  # min bet value
  minBet: 10
  # max bet value
  maxBet: 100
  # sustain_percent_of
  sustainPercent: 25,
  # user stake will be multiplied by this factor if correct wire chosen
  stakeMultiplicator: 2
  # if positive, countdown message will be sent every X seconds (5 = 5s)
  showStatusInterval: 10
  # if positive, shows countdow every X seconds (5 = 5s)
  showDecisionReminderInterval: 15
  # fee on game resignation (if user won 10 coins, 9 coins will be sent to user account, 1 to bot's payout account)
  fee: 1
  # payout pot account name
  potAccountName: timebomb_pot
  # rain pot account name
  rainPotAccountName: timebomb_rainpot
commands:
  help:
    pm: true
    channel: true
    guest: true
  tip:
    pm: false
    channel: true
  balance:
    pm: true
    channel: true
    guest: true
  withdraw:
    pm: true
    channel: false
  address:
    pm: true
    channel: false
  terms:
    pm: true
    channel: false
    guest: true
  rain:
    pm: false
    channel: true
  rainactive:
    enabled: true
    pm: false
    channel: true
  bomb:
    pm: false
    channel: true
  again:
    pm: false
    channel: true
  stop:
    pm: false
    channel: true
  cutwire:
    pm: false
    channel: true
  cut:
    pm: false
    channel: true
  pot:
    pm: false
    channel: true
  listaccounts:
    pm: false
    channel: false
  listcommands:
    pm: false
    channel: false
  info:
    pm: false
    channel: true
    guest: true
  val:
    pm: false
    channel: true
    guest: true
  version:
    pm: false
    channel: true
    guest: true
  height:
    pm: false
    channel: true
    guest: true
  diff:
    pm: false
    channel: true
    guest: true
  donate:
    pm: false
    channel: true
    guest: true
  total:
    pm: false
    channel: true
  adminhelp:
    pm: true
    channel: true
  uptime:
    pm: false
    channel: true
    guest: true
messages:
  error: 'Sorry %name%, something went wrong.'
  no_funds: '%reset%Sorry%light_red% %name%%reset%, you %light_red% Don''t%reset%have enough funds (you''re%light_red% %short%%reset%%short_name%%reset%short)'
  not_identified: '%light_red% %name%%reset%: You need to be identified with %light_red% NickServ %reset%to Abuse me :P - %light_red% /msg nickserv help identify.'
  tipped: '%light_green%%from%%reset%tipped%light_green% %to% %amount% %reset%%short_name%! - Sponsored by%light_green% %from%'
  balance: '%name% has %balance% %short_name%.'
  balance_unconfirmed: '%light_green%%name%%reset% has %light_green%%balance%%reset% %short_name% (unconfirmed:%yellow%%unconfirmed%%reset% %short_name%) - Sponsored by%light_green% The HyperStake Community'
  deposit_address: 'Your deposit address %address%'
  withdraw_too_small: 'Sorry %name%, you need to withdraw at least %min_withdraw% %short_name% (you have %balance% %short_name%)'
  invalid_address: 'Sorry %name%, the address you specified is invalid (%address%).'
  tip_too_small: '%reset%Sorry%light_red% %from%%reset%, your tip to%light_red% %to%%reset%is too small [min.%light_red% %min_tip%%reset%%short_name%].'
  rain_too_small: '%reset%Sorry%light_red% %from%%reset%, your rain is too small [min.%light_red% %min_rain%%reset%%short_name%]. %light_red%Increase%reset%the%light_red% Value%reset%or %light_red%Decrease%reset%the%light_red% Max%reset%users.'
  tip_self: '%light_red%%name%%reset%, Sucking ur self off in public is%light_red% Embarrassing%reset%!'
  invalid_amount: 'Sorry %name%, ''%amount%'' is not a correct amount.'
  rain: '%light_green%%name%%reset%rained%light_green% %amount%%reset%%short_name% upon%light_green% %list%%reset%. - Sponsored by%light_green% %name%'
  withdraw_success:
    - '%name%: %amount%%short_name% has been withdrawn from your account to %address%'
    - 'You have been charged %withdrawal_fee% %short_name% withdrawal fee.'
    - 'Transaction %transaction% completed.'
  partial_withdraw_success:
    - '%name%: %amount%%short_name% has been withdrawn from your account to %address%'
    - 'You have been charged %withdrawal_fee% %short_name% withdrawal fee.'
    - 'You have %amount_left% %short_name% left in your account.'
    - 'Transaction %transaction% completed.'
  help:
    - 'You can use following commands in channel:'
    - '%prefix%balance - displays your current wallet balance'
    - '%prefix%tip <nick> <amount> - sends the specified amount of %full_name% to the specified nickname'
    - '%prefix%rain <amount> [max] - splits amount coins between max users or the whole channel'
    - '%prefix%rainactive <amount> [active X minutes ago] - as rain, but only to active chatters'
    - '%prefix%terms - displays terms and conditions for using %nick%'
    - '%prefix%bomb	<amount> - (TimeBomb) start game with given bet'
    - '%prefix%cutwire <color> - (TimeBomb) cut wire of given color'
    - '%prefix%again - (TimeBomb) play next round'
    - '%prefix%stop - (TimeBomb) resign and take profit'
    - '%prefix%val [amount] <currency> <currency> - if no amount is given default of 1 is used'
    - '%prefix%diff - displays current difficulty'
    - '%prefix%height - displays current block height'
    - '%prefix%info - displays specific coin info'
    - '%prefix%donate - displays donation info'
    - 'You MUST PM %nick% the following Commands'
    - 'address - displays %full_name% address where you can send your funds to the tip bot'
    - 'withdraw <%full_name% address> [amount] - withdraws your wallet balance (or partial amount if given) to specified address (you will be charged %withdrawal_fee%%short_name% withdrawal fee)'
    - 'Help END'
  donate:
    - 'If you like my work on Matylda and would like to donate to future development, Please use ANY of the following Addresses:-'
    - 'HYP - pDrew9zwzrX5iwX6ef6P7SboHz5oQfqoou'
    - 'BTC - 1EjzZ78WtpiDKxXk3byuUgPPBszhDPR6Rm'
    - 'Alternatively, you may %prefix%tip Matylda [amount]'
    - 'Help END'
  adminhelp:
    - 'total - Displays the Current bot Total Balance'
    - 'check <nick> - Returns a Users Current Balance'
    - 'move <nick> <nick> <amount> - Moves an Amount from one Account to another Account'
    - 'Help END'
  terms:
    - 'There are no fees to use %nick%, with the exception of %withdrawal_fee%%short_name% fee on withdrawals.'
    - 'In no event shall %nick% be responsible in the event of lost, stolen or misdirected funds.'
  info: '%reset%Coin: %magenta%%short_name%%reset% | Height:%light_blue% %blocks%%reset%| PoS Diff:%light_blue% %pos_diff%%reset%| Money Supply:%light_blue% %moneysupply%%reset%| Connections:%light_blue% %connectioncount%.'
  version: '%reset%Coin:%light_blue% %short_name%%reset%| %light_blue%Daemon%reset%Version:%light_blue% %version%%reset%| %light_blue%Bot%reset%Version:%light_blue% 1.1.22 %reset%-%light_blue% 27-02-2015'
  height: '%reset%Coin:%light_blue% %short_name%%reset%| Current Height:%light_blue% %height%.'
  diff: '%reset%Coin:%light_blue% %short_name%%reset%| Current:%light_blue% %diff%%reset%| High:%light_blue% %ath%%reset%| Low:%light_blue% %atl%'
  total: 'Total Balance:%orange% %total% %reset%%short_name%'
  uptime: 'Total bot uptime: %uptime%'
  timebomb:
    usage: 'Usage: %prefix%bomb <amount>, min. bet %min_bet%, max. bet %max_bet%.'
    cutwireusage: 'Usage: %prefix%cutwire <color>'
    nosuchcolor: 'There is no such wire!'
    bombactivation: 'ROUND %round%: Diffuse the bomb by cutting the correct wire (%prefix%cutwire <color>). There are %wiresCount% wires. They are %wiresColors%.'
    bombalreadyactivated: 'Bomb already activated. %player% tries to diffuse it. %timeLeft% seconds left...'
    gameinprogress: 'Game already in progress. Player: %player%'
    timeleft: 'Hurry up! %timeLeft% seconds left...'
    correct: 'Correct! Reward %reward% %short_name% - your balance is now %balance% %short_name% - %prefix%again to try double again or %prefix%stop to withdraw (withdrawal fee %fee% %short_name%)'
    timeisup: 'Time is up!!!'
    boom: '***BOOM*** %player% loses - %lost_amount% %short_name% deposited in rain pot, rain @ %max_rain_fund% %short_name% :: [RainPot %rain_pot_balance% %short_name%] [Pot %pot_balance% %short_name%]'
    resign: 'Congratulations! You''ve won %won% %short_name% (-fee, includes your bet). Check your balance with %prefix%balance anytime'
    potoverflow: 'Pot reached its limit! Now will rain!'
    wrongbet: 'Sorry, bet has to be between %min_bet% and %max_bet% %short_name%'
    nofunds: 'Sorry, you don''t have so many %short_name%'
    nofundsinpot: 'Sorry, next doubling is not possible, pot has only %pot_balance% %short_name%'
    nofundsinpottostart: 'Sorry, pot is too low on funds to start new game with that bet, try lower bet'
    decisiontimeleft: 'Waiting for decision (%prefix%again or %prefix%stop) just for %time_left% seconds, otherwise your balance will be lost...'
    decisiontimeisup: 'Sorry! No decision so balance is deposited in pot. Ready for new player.'
    potinfo: 'BombRain pot has %rain_pot_balance% %short_name%, BombFund pot has %pot_balance% %short_name%, rain @ %max_rain_fund% %short_name%'
  val:
    usage: 'Usage: %prefix%val [amount, default:1] btc eur, eg. %prefix%val 10 btc usd, %prefix%val hyp btc'
    error: 'Error: bad request, derp, try again'
    exchanged: '%reset%Currently%light_blue% %amount% %base% %reset%is worth%light_blue% %value% %target% %reset%(exchanged at%light_blue% %price% %target%%reset%) - Source 8==D %light_blue%Cryptonator'
